apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend
    spec:  
      containers:  
        - name: backend
          image: asia.gcr.io/stellar-38931/testnft:master
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
      restartPolicy: Always

